namespace RagWorkspace.Api.Interfaces;

/// <summary>
/// Interface for services that provide text embedding functionality
/// </summary>
public interface IEmbeddingProvider
{
    /// <summary>
    /// Generates an embedding vector for the provided text
    /// </summary>
    /// <param name="text">The text to generate an embedding for</param>
    /// <returns>A float array representing the embedding vector</returns>
    Task<float[]> GenerateEmbeddingAsync(string text);
    
    /// <summary>
    /// Gets the dimensionality of the embedding vectors generated by this provider
    /// </summary>
    /// <returns>The size of the embedding vector</returns>
    int GetEmbeddingVectorSize();
    
    /// <summary>
    /// Gets the name of the provider
    /// </summary>
    /// <returns>The provider name</returns>
    string GetProviderName();
}